name: nightly
on: push
jobs:
  my-job:
    strategy:
      #fail-fast: true
      matrix:
          os: [  'el7' ]
         # os: [ 'el7', 'el8', 'el9', 'd10', 'd12', 'u18', 'u20' ]
      
    runs-on: ubuntu-latest
   
    container: 
      image: ghcr.io/perfsonar/unibuild/${{ matrix.os }}:latest
        
    steps:
       - name: Copy repo
         uses: actions/checkout@v2
       - name: install dependancies repo
         run: dnf -y install -y http://linux.mirrors.es.net/perfsonar/${{ matrix.os }}/x86_64/5/packages/perfsonar-repo-0.11-1.noarch.rpm
       
       - name: make
         run: make
  
       - name: tar files
         run: tar -cvf graphs.tar ./unibuild-repo
  
       - name: Archive RPM
         uses: actions/upload-artifact@v2
         with:
           name: perfsonar-graphs-${{ matrix.os }}.tar
           path: graphs.tar
