name: Nightly build

on:
  schedule:
    - cron: '1 1 * * *'
  push:
  
jobs:
  build:

    runs-on: ghcr.io/perfsonar/unibuild/el8:latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: '5.0.5'
        
    - name: Start unibuild
      run: make
