name: Nightly build

on:
  push:
    branches: [ 5.0.5 ]
  
jobs:
  build:

    runs-on: unbuntu-latest
    container: 
      image: ghcr.io/perfsonar/unibuild/el8:latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: '5.0.5'
        
    - name: Start unibuild
      run: make
