name: nightly
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/perfsonar/unibuild/el9:latest
      
    steps:
      - name: install git
        run: dnf -y install git
      
      - name: git repo
        run: git clone https://github.com/perfsonar/graphs.git
        
      - name: make
        working-directory: ./graphs
        run: make
