name: nightly
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/perfsonar/unibuild/el9:latest
      
    steps:
      - name: list
        run: ls -al;pwd
        
      - name: install git
        run: dnf -y install git
      # make sure to check out the correct branch
      - name: git repo
        run: git clone https://github.com/perfsonar/graphs.git

      - name: install dependancies repo
        run: dnf -y install -y http://linux.mirrors.es.net/perfsonar/el9/x86_64/5/packages/perfsonar-repo-0.11-1.noarch.rpm
     
      - name: make
        working-directory: ./graphs
        run: make
