name: nightly
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/perfsonar/unibuild/el9:latest
      
    steps:
      - name: list
        run: ls -al;pwd
        
      - name: install git
        run: dnf -y install git
      # make sure to check out the correct branch
      - name: git repo
        run: git clone https://github.com/perfsonar/graphs.git

      - name: install dependancies repo
        run: dnf -y install -y https://perfsonar-dev3.grnoc.iu.edu/nightly/el/9/x86_64/perfsonar/minor/packages/perfsonar-repo-nightly-minor-0.11-0.20230721201931.el9.noarch.rpm
     
      - name: make
        working-directory: ./graphs
        run: make
